services:
  mariadb:
    image: mariadb:10.6.21
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: r00tP@ssw0rd!
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mariadb

volumes:
  db_data:
    driver: local
