services:
  mysql:
    image: mysql:8.4
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mysql

volumes:
  db_data:
    driver: local
